CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE TABLE IF NOT EXISTS places (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 osm_type VARCHAR(16) NOT NULL,
 osm_id BIGINT NOT NULL,
 name TEXT, name_ja TEXT,
 amenity TEXT, shop TEXT, tourism TEXT, leisure TEXT, office TEXT, healthcare TEXT,
 cuisine TEXT, brand TEXT, opening_hours TEXT, address TEXT,
 tags JSONB NOT NULL DEFAULT '{}',
 lat DOUBLE PRECISION NOT NULL CHECK (lat BETWEEN -90 AND 90),
 lng DOUBLE PRECISION NOT NULL CHECK (lng BETWEEN -180 AND 180),
 geom geography(Point,4326) NOT NULL,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE(osm_type,osm_id)
);
CREATE INDEX IF NOT EXISTS places_geom_idx ON places USING GIST(geom);
CREATE INDEX IF NOT EXISTS places_name_trgm_idx ON places USING GIN(name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_name_ja_trgm_idx ON places USING GIN(name_ja gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_brand_trgm_idx ON places USING GIN(brand gin_trgm_ops);
